package com.dofull.huadong.g51;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * TodoWorkItemWSForEastChina service = new TodoWorkItemWSForEastChina();
 * TodoWorkItemWSForEastChina portType = service.getTodoWorkItemWSForEastChinaPort();
 * portType.getTodoItems(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "TodoWorkItemWSForEastChina", targetNamespace = "http://g51.huadong.dofull.com/", wsdlLocation = "file:/C:/Users/Administrator/Desktop/TodoWorkItemWSForEastChina.wsdl")
public class TodoWorkItemWSForEastChina_Service extends Service {

	private final static URL TODOWORKITEMWSFOREASTCHINA_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.dofull.huadong.g51.TodoWorkItemWSForEastChina_Service.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.dofull.huadong.g51.TodoWorkItemWSForEastChina_Service.class
					.getResource(".");
			url = new URL(baseUrl,
					"file:/C:/Users/Administrator/Desktop/TodoWorkItemWSForEastChina.wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Administrator/Desktop/TodoWorkItemWSForEastChina.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		TODOWORKITEMWSFOREASTCHINA_WSDL_LOCATION = url;
	}

	public TodoWorkItemWSForEastChina_Service(URL wsdlLocation,
			QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public TodoWorkItemWSForEastChina_Service() {
		super(TODOWORKITEMWSFOREASTCHINA_WSDL_LOCATION, new QName(
				"http://g51.huadong.dofull.com/", "TodoWorkItemWSForEastChina"));
	}

	/**
	 * 
	 * @return returns TodoWorkItemWSForEastChina
	 */
	@WebEndpoint(name = "TodoWorkItemWSForEastChinaPort")
	public TodoWorkItemWSForEastChina getTodoWorkItemWSForEastChinaPort() {
		return super.getPort(new QName("http://g51.huadong.dofull.com/",
				"TodoWorkItemWSForEastChinaPort"),
				TodoWorkItemWSForEastChina.class);
	}

}
