package com.jiuqi.kgj.workitem.send.webservice.todoservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-10-18T14:26:16.636+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/", name = "ISynTodoInfoWs")
public interface ISynTodoInfoWs {

    @WebMethod
    @RequestWrapper(localName = "getTodoData", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/", className = "com.jiuqi.kgj.workitem.send.webservice.todoservice.GetTodoData")
    @ResponseWrapper(localName = "getTodoDataResponse", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/", className = "com.jiuqi.kgj.workitem.send.webservice.todoservice.GetTodoDataResponse")
    @WebResult(name = "return", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/")
    public java.lang.String getTodoData(
        @WebParam(name = "input", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/")
        java.lang.String input
    );

    @WebMethod
    @RequestWrapper(localName = "getDisposeData", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/", className = "com.jiuqi.kgj.workitem.send.webservice.todoservice.GetDisposeData")
    @ResponseWrapper(localName = "getDisposeDataResponse", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/", className = "com.jiuqi.kgj.workitem.send.webservice.todoservice.GetDisposeDataResponse")
    @WebResult(name = "return", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/")
    public java.lang.String getDisposeData(
        @WebParam(name = "input", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/")
        java.lang.String input
    );

    @WebMethod
    @RequestWrapper(localName = "getPurchaseData", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/", className = "com.jiuqi.kgj.workitem.send.webservice.todoservice.GetPurchaseData")
    @ResponseWrapper(localName = "getPurchaseDataResponse", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/", className = "com.jiuqi.kgj.workitem.send.webservice.todoservice.GetPurchaseDataResponse")
    @WebResult(name = "return", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/")
    public java.lang.String getPurchaseData(
        @WebParam(name = "input", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/")
        java.lang.String input
    );

    @WebMethod
    @RequestWrapper(localName = "getAlterData", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/", className = "com.jiuqi.kgj.workitem.send.webservice.todoservice.GetAlterData")
    @ResponseWrapper(localName = "getAlterDataResponse", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/", className = "com.jiuqi.kgj.workitem.send.webservice.todoservice.GetAlterDataResponse")
    @WebResult(name = "return", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/")
    public java.lang.String getAlterData(
        @WebParam(name = "input", targetNamespace = "http://todoservice.webservice.send.workitem.kgj.jiuqi.com/")
        java.lang.String input
    );
}
